// import R from '@theme';

// export enum THEME_CONSTANTS {
//   MARGIN_VERTICAL = R.unit.scale(20),
//   MARGIN_TOP = R.unit.scale(20),
//   MARGIN_BOTTOM = R.unit.scale(20),
//   MARGIN_HORIZONTAL = R.unit.scale(21),
//   MARGIN_LEFT = R.unit.scale(10),
//   MARGIN_RIGHT = R.unit.scale(10),
//   MARGIN_LEFT_5 = R.unit.scale(5),
//   MARGIN_RIGHT_15 = R.unit.scale(15),
//   PADDING_HORIZONTAL = R.unit.scale(21),
//   PADDING_VERTICAL = R.unit.scale(23),
//   PADDING_TOP = R.unit.scale(5),
//   PADDING_BOTTOM = R.unit.scale(5),
//   PADDING = R.unit.scale(10),
//   PADDING_2 = R.unit.scale(2),
//   WIDTH = R.unit.scale(300),
//   HEIGHT = R.unit.scale(50),
//   SCREEN_WRAPPER_PADDING_TOP_ANDROID = 0,
//   SCREEN_WRAPPER_PADDING_TOP_IOS = R.unit.scale(80),
//   BORDER_RADIUS = R.unit.scale(25),
//   DRAWER_BORDER_BOTTOM_RIGHT_RADIUS_IOS = R.unit.scale(20),
//   DRAWER_BORDER_TOP_RIGHT_RADIUS_IOS = R.unit.scale(20),
//   DRAWER_BORDER_BOTTOM_RIGHT_RADIUS_ANDROID = 0,
//   DRAWER_BORDER_TOP_RIGHT_RADIUS_ANDROID = 0,
// }
